version: '3'

services:
  app:
    image: furacas/chat-api-proxy:latest
    container_name: chat-api-proxy
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      API_KEYS: chat-api-proxy-api-key